### ISSUE TITLE
 1. Import data using the console 

### ISSUE THREAD

**Issue by msutton150** [roitraining/sbcl-public#3]
Step 2.2 instructions: Link Wrong.
Define an explicit schema, using the information found in gs://sb-challenge-labs/data_analyst/schemas/branches.csv

Should be https://storage.googleapis.com/sb-challenge-labs/data_analyst/schemas/branches.json

**Comment by jwdavis** [comment]
mike, I think this issue should be in the class-specific repo, not the
public repo?

Is this for the analyst class?

Thanks,

jwd


--


Director, Strategy and Customer Success

ROI Training

408.759.4664

calendar
<https://calendar.google.com/calendar/embed?src=c_f0b8qbcdd7kk0srmmo44ionj18%40group.calendar.google.com&ctz=America%2FLos_Angeles&src=jeff%40roitraining.com&src=jeff%40jwdavis.me>

**Comment by jwdavis** [comment]
resolved in the da repo.
